#!/bin/bash
# Instructions to generate PDF from the research report

echo "======================================"
echo "Generate PDF from Research Report"
echo "======================================"
echo ""
echo "METHOD 1 - Using Browser (Easiest):"
echo "  1. Open report.html in Chrome/Firefox/Edge"
echo "  2. Press Ctrl+P (or Cmd+P on Mac)"
echo "  3. Select 'Save as PDF' as destination"
echo "  4. Click 'Save'"
echo ""
echo "METHOD 2 - Using Command Line (if wkhtmltopdf installed):"
echo "  wkhtmltopdf report.html EvapoScore_Research_Report.pdf"
echo ""
echo "METHOD 3 - Using Pandoc (if installed):"
echo "  pandoc RESEARCH_REPORT.md -o EvapoScore_Research_Report.pdf"
echo ""
echo "METHOD 4 - Online Converter:"
echo "  Upload report.html to: https://www.html2pdf.com"
echo ""
echo "Files available:"
echo "  - report.html (styled web version)"
echo "  - RESEARCH_REPORT.md (markdown version)"
echo "======================================"
